version: '3.9'

services:
  eureka-server:
    image: openjdk:17-jdk-alpine
    container_name: eureka-server
    ports:
      - "8671:8671"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./eureka:/app
    command: >
      sh -c "java -jar /app/eureka-server.jar"
    networks:
      - app-network

  service-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-client
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:clientDB
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_APPLICATION_NAME: SERVICE-CLIENT
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8671/eureka/
    depends_on:
      - eureka-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
